import React, { useState } from 'react';
import {
  Sparkles,
  GitBranch,
  GitCommit,
  Rocket,
  CheckCircle2,
  Code,
  FileCode,
  ArrowRight,
  Terminal,
  Layers,
  ChevronDown,
  ChevronUp,
  AlertCircle
} from 'lucide-react';
import { Project } from '../../context/DataProvider';

interface ApprovedDreamsPushPanelProps {
  project: Project;
  updateProject: (projectId: string, updates: Partial<Project>) => void;
  onSuccessToast?: (msg: string) => void;
}

export const ApprovedDreamsPushPanel: React.FC<ApprovedDreamsPushPanelProps> = ({
  project,
  updateProject,
  onSuccessToast,
}) => {
  const [pushingId, setPushingId] = useState<string | null>(null);
  const [isBulkPushing, setIsBulkPushing] = useState(false);
  const [expandedSnippets, setExpandedSnippets] = useState<Record<string, boolean>>({});
  const [selectedBranch, setSelectedBranch] = useState('main');
  const [lastMergedCommit, setLastMergedCommit] = useState<{
    sha: string;
    title: string;
    targetFile: string;
    branch: string;
  } | null>(null);

  const approvedDreams = (project.dreamRecommendations || []).filter(
    (d: any) => d.status === 'approved'
  );

  const mergedDreams = (project.dreamRecommendations || []).filter(
    (d: any) => d.status === 'merged'
  );

  const handlePushDreamToMain = async (dream: any) => {
    setPushingId(dream.id);

    // Simulate fast realistic Git merge & verification pipeline
    await new Promise((resolve) => setTimeout(resolve, 600));

    const commitSha = `c1a${Math.random().toString(36).substring(2, 9)}`;
    const cleanTitle = dream.title.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase();
    const targetFilePath = `src/features/${cleanTitle}.ts`;

    // 1. Merge the code snippet into the project's virtualFiles
    const currentFiles = project.virtualFiles || {};
    const updatedFiles = {
      ...currentFiles,
      [targetFilePath]: `/**
 * Aether Dream Optimization: ${dream.title}
 * Commit SHA: ${commitSha}
 * Branch: ${selectedBranch}
 * Timestamp: ${new Date().toISOString()}
 */

${dream.snippet || '// Implementation generated by Aether Autonomous Dreaming'}
`,
    };

    // 2. Add Git Commit record
    const newCommit = {
      id: commitSha,
      message: `feat(aether-dream): ${dream.title}`,
      author: 'Aether Autonomous Agent',
      timestamp: Date.now(),
      branch: selectedBranch,
      filesChanged: [targetFilePath],
    };

    const updatedCommits = [newCommit, ...(project.gitCommits || [])];

    // 3. Mark the dream recommendation as 'merged'
    const updatedRecs = (project.dreamRecommendations || []).map((d: any) => {
      if (d.id === dream.id) {
        return {
          ...d,
          status: 'merged' as const,
          mergedAt: Date.now(),
          mergedCommitSha: commitSha,
          mergedBranch: selectedBranch,
        };
      }
      return d;
    });

    // 4. Update the project record
    updateProject(project.id, {
      virtualFiles: updatedFiles,
      gitCommits: updatedCommits as any,
      dreamRecommendations: updatedRecs,
    });

    setLastMergedCommit({
      sha: commitSha,
      title: dream.title,
      targetFile: targetFilePath,
      branch: selectedBranch,
    });

    setPushingId(null);
    if (onSuccessToast) {
      onSuccessToast(`Pushed "${dream.title}" to ${selectedBranch} branch! (Commit: ${commitSha})`);
    }
  };

  const handleBulkPushAll = async () => {
    if (approvedDreams.length === 0) return;
    setIsBulkPushing(true);

    for (const dream of approvedDreams) {
      await handlePushDreamToMain(dream);
    }

    setIsBulkPushing(false);
    if (onSuccessToast) {
      onSuccessToast(`All ${approvedDreams.length} approved dreams successfully merged to ${selectedBranch}!`);
    }
  };

  return (
    <div className="bg-[#121214] border border-zinc-800 rounded-xl p-5 shadow-lg space-y-4 font-sans">
      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 border-b border-zinc-800/80 pb-3">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-xl bg-indigo-500/10 border border-indigo-500/25 text-indigo-400 flex items-center justify-center">
            <Sparkles size={16} />
          </div>
          <div>
            <h3 className="text-xs font-bold text-zinc-100 flex items-center gap-2">
              <span>Approved Aether Dreams Pipeline</span>
              <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/25 text-emerald-300">
                {approvedDreams.length} Ready to Push
              </span>
              {mergedDreams.length > 0 && (
                <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-indigo-500/10 border border-indigo-500/25 text-indigo-300">
                  {mergedDreams.length} Merged to Main
                </span>
              )}
            </h3>
            <p className="text-[11px] text-zinc-400">
              Autonomous AI dream proposals approved by you. Push directly into your live repository codebase.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 self-end sm:self-auto">
          <div className="flex items-center gap-1.5 bg-zinc-900 border border-zinc-800 rounded-lg px-2.5 py-1 text-xs font-mono text-zinc-300">
            <GitBranch size={12} className="text-indigo-400" />
            <span className="text-[10px] text-zinc-500">Target:</span>
            <select
              value={selectedBranch}
              onChange={(e) => setSelectedBranch(e.target.value)}
              className="bg-transparent text-white font-bold outline-none cursor-pointer"
            >
              <option value="main">main</option>
              <option value="develop">develop</option>
              <option value="aether-staging">aether-staging</option>
            </select>
          </div>

          {approvedDreams.length > 1 && (
            <button
              onClick={handleBulkPushAll}
              disabled={isBulkPushing}
              className="px-3 py-1.5 bg-emerald-500 hover:bg-emerald-400 disabled:opacity-50 text-black text-xs font-bold rounded-lg transition-all shadow-md flex items-center gap-1.5 cursor-pointer"
            >
              <Rocket size={13} />
              {isBulkPushing ? 'Pushing All...' : `Push All to ${selectedBranch} (${approvedDreams.length}) 🚀`}
            </button>
          )}
        </div>
      </div>

      {/* Last Merge Alert Success Toast Banner */}
      {lastMergedCommit && (
        <div className="bg-emerald-950/40 border border-emerald-500/30 rounded-xl p-3.5 flex items-center justify-between gap-3 animate-in fade-in slide-in-from-top-2 duration-200">
          <div className="flex items-center gap-2.5 text-xs">
            <CheckCircle2 size={16} className="text-emerald-400 shrink-0" />
            <div>
              <span className="font-bold text-emerald-200">
                Pushed "{lastMergedCommit.title}" to {lastMergedCommit.branch}!
              </span>
              <span className="text-zinc-400 font-mono text-[10px] ml-2">
                Commit: <code className="text-emerald-400 bg-emerald-950/60 px-1 py-0.5 rounded">{lastMergedCommit.sha}</code> &bull; Target File: <code className="text-zinc-300">{lastMergedCommit.targetFile}</code>
              </span>
            </div>
          </div>
          <button
            onClick={() => setLastMergedCommit(null)}
            className="text-[10px] text-zinc-400 hover:text-white underline cursor-pointer"
          >
            Dismiss
          </button>
        </div>
      )}

      {/* Approved Dreams Listing */}
      {approvedDreams.length > 0 ? (
        <div className="space-y-3">
          {approvedDreams.map((dream: any) => {
            const isPushing = pushingId === dream.id;
            const isSnippetOpen = expandedSnippets[dream.id] || false;

            return (
              <div
                key={dream.id}
                className="bg-zinc-950/60 border border-zinc-850 hover:border-indigo-500/40 rounded-xl p-4 transition-all shadow-md space-y-3"
              >
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                  <div className="space-y-1 flex-1">
                    <div className="flex items-center gap-2">
                      <span className="text-[9px] font-mono px-2 py-0.5 rounded-full bg-indigo-500/10 border border-indigo-500/25 text-indigo-300 font-bold uppercase">
                        {dream.category || 'refactor'} focus
                      </span>
                      <span className="text-[9px] font-mono text-zinc-500">
                        Created: {new Date(dream.createdAt || Date.now()).toLocaleDateString()}
                      </span>
                    </div>
                    <h4 className="text-xs font-bold text-zinc-100">{dream.title}</h4>
                    <p className="text-[11px] text-zinc-400 leading-relaxed font-sans">
                      {dream.description}
                    </p>
                  </div>

                  <div className="flex items-center gap-2 shrink-0">
                    <button
                      onClick={() =>
                        setExpandedSnippets((prev) => ({
                          ...prev,
                          [dream.id]: !isSnippetOpen,
                        }))
                      }
                      className="px-2.5 py-1.5 bg-zinc-900 hover:bg-zinc-850 text-zinc-400 hover:text-zinc-200 border border-zinc-800 rounded-lg text-xs font-mono flex items-center gap-1 transition-colors cursor-pointer"
                    >
                      <Code size={12} />
                      {isSnippetOpen ? 'Hide AST' : 'View AST'}
                      {isSnippetOpen ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
                    </button>

                    <button
                      onClick={() => handlePushDreamToMain(dream)}
                      disabled={isPushing}
                      className="px-4 py-1.5 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white text-xs font-bold rounded-lg transition-all shadow-md shadow-indigo-600/20 flex items-center gap-1.5 cursor-pointer font-mono"
                    >
                      <Rocket size={13} className={isPushing ? 'animate-spin' : ''} />
                      {isPushing ? 'Pushing...' : `Push to ${selectedBranch} 🚀`}
                    </button>
                  </div>
                </div>

                {/* Expandable Snippet Preview */}
                {isSnippetOpen && (
                  <div className="space-y-1.5 pt-2 border-t border-zinc-900 animate-in fade-in duration-150">
                    <div className="flex items-center justify-between text-[10px] font-mono text-zinc-500">
                      <span>Code Injection Target: src/features/{dream.title.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()}.ts</span>
                      <span className="text-indigo-400">TypeScript AST</span>
                    </div>
                    <pre className="p-3 bg-[#0a0a0c] border border-zinc-900 rounded-lg text-[10px] font-mono text-zinc-300 overflow-x-auto select-text leading-relaxed">
                      <code>{dream.snippet || '// Implementation generated by Aether Autonomous Dreaming'}</code>
                    </pre>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      ) : (
        <div className="p-6 text-center border border-dashed border-zinc-850 rounded-xl bg-zinc-950/30 flex flex-col items-center justify-center gap-2">
          <Sparkles size={24} className="text-zinc-600" />
          <p className="text-xs text-zinc-400 font-semibold">No approved dreams pending push.</p>
          <p className="text-[11px] text-zinc-500 max-w-sm">
            Review recommendations in the AI Dream Deck below, click "Approve", and they will appear here ready to push to your main branch!
          </p>
        </div>
      )}

      {/* Merged Dreams History */}
      {mergedDreams.length > 0 && (
        <div className="pt-3 border-t border-zinc-850 space-y-2">
          <span className="text-[10px] uppercase font-bold text-zinc-500 font-mono tracking-wider block">
            Previously Merged Dreams ({mergedDreams.length})
          </span>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
            {mergedDreams.map((m: any) => (
              <div
                key={m.id}
                className="bg-zinc-950/40 border border-zinc-900 rounded-lg p-2.5 flex items-center justify-between gap-2 text-xs"
              >
                <div className="flex items-center gap-2 truncate">
                  <CheckCircle2 size={13} className="text-emerald-400 shrink-0" />
                  <span className="text-zinc-300 font-medium truncate">{m.title}</span>
                </div>
                <span className="text-[9px] font-mono text-indigo-400 bg-indigo-950/50 border border-indigo-500/20 px-1.5 py-0.5 rounded shrink-0">
                  {m.mergedBranch || 'main'}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default ApprovedDreamsPushPanel;
